services:
  app:
    image: node:20-bookworm-slim
    working_dir: /app
    ports:
      - "3002:3000"
    volumes:
      - ./:/app
    command: ["sh", "-c", "npm ci && npm run dev"]
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.development